"""Registry of EIA API routes across all energy categories.

Route data is loaded from bundled JSON files in ``_route_data/``, which are
generated by ``scripts/discover_routes.py``.  This means route discovery is
a development-time step -- users do not need an API key just to see what
routes exist.
"""

from __future__ import annotations

import json
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any


@dataclass(frozen=True)
class RouteInfo:
    """Metadata for a single leaf route in the EIA API."""
    path: str
    frequencies: list[str] = field(default_factory=list)
    facets: list[str] = field(default_factory=list)
    data_columns: list[str] = field(default_factory=list)


@dataclass(frozen=True)
class RouteGroup:
    """A named group of related route variants."""
    default: str
    routes: dict[str, RouteInfo]


class RouteRegistry:
    """Central registry of all known EIA API routes.

    Loads route data from bundled JSON files at construction time.
    """

    def __init__(self) -> None:
        self._categories: dict[str, dict[str, RouteGroup]] = {}
        self._load_bundled()

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    def list_categories(self) -> list[str]:
        """Return sorted list of all known categories."""
        return sorted(self._categories)

    def list_groups(self, category: str) -> dict[str, list[str]]:
        """Return ``{group_name: [variant_names]}`` for *category*."""
        groups = self._get_category(category)
        return {g: sorted(rg.routes) for g, rg in groups.items()}

    def resolve(
        self, category: str, group: str, variant: str | None = None
    ) -> str:
        """Return the full EIA route path for *category* / *group* / *variant*.

        Passing ``variant=None`` yields the group's default route.
        """
        groups = self._get_category(category)
        try:
            rg = groups[group]
        except KeyError:
            raise ValueError(
                f"Unknown route group {group!r} in category {category!r}. "
                f"Valid groups: {sorted(groups)}."
            ) from None
        key = variant if variant is not None else rg.default
        try:
            return rg.routes[key].path
        except KeyError:
            raise ValueError(
                f"Unknown variant {variant!r} for {group!r} in {category!r}. "
                f"Valid variants: {sorted(rg.routes)}."
            ) from None

    def get_route_info(
        self, category: str, group: str, variant: str | None = None
    ) -> RouteInfo:
        """Return the ``RouteInfo`` for the resolved route."""
        groups = self._get_category(category)
        try:
            rg = groups[group]
        except KeyError:
            raise ValueError(
                f"Unknown route group {group!r} in category {category!r}."
            ) from None
        key = variant if variant is not None else rg.default
        try:
            return rg.routes[key]
        except KeyError:
            raise ValueError(
                f"Unknown variant {variant!r} for {group!r} in {category!r}."
            ) from None

    # ------------------------------------------------------------------
    # Loading
    # ------------------------------------------------------------------

    def _load_bundled(self) -> None:
        """Load all JSON files from the _route_data directory."""
        data_dir = Path(__file__).parent / "_route_data"
        if not data_dir.is_dir():
            return
        for json_file in sorted(data_dir.glob("*.json")):
            slug = json_file.stem  # e.g. "natural_gas"
            category = slug.replace("_", "-")  # -> "natural-gas"
            try:
                data = json.loads(json_file.read_text())
            except (json.JSONDecodeError, OSError):
                continue
            self._categories[category] = self._build_groups(data, category)

    def _build_groups(
        self, data: dict[str, Any], category: str
    ) -> dict[str, RouteGroup]:
        """Convert discovered JSON data into RouteGroup objects.

        Groups routes by their second path segment.  For example,
        ``natural-gas/cons/sum`` and ``natural-gas/cons/num`` both go
        into the ``cons`` group with variants ``sum`` and ``num``.

        For flat categories with only one leaf (e.g. ``crude-oil-imports``),
        a single group named ``data`` is created.
        """
        leaves: list[dict[str, Any]] = data.get("leaves", [])
        if not leaves:
            return {}

        # Group leaves by their second path segment
        grouped: dict[str, dict[str, RouteInfo]] = {}
        for leaf in leaves:
            route_path: str = leaf.get("route", "")
            parts = route_path.split("/")
            if len(parts) >= 3:
                group_name = parts[1]
                variant_name = "/".join(parts[2:])
            elif len(parts) == 2:
                group_name = parts[1]
                variant_name = parts[1]
            else:
                group_name = "data"
                variant_name = "data"

            info = RouteInfo(
                path=route_path,
                frequencies=leaf.get("frequency", []),
                facets=leaf.get("facets", []),
                data_columns=leaf.get("data_columns", []),
            )
            grouped.setdefault(group_name, {})[variant_name] = info

        # Build RouteGroup objects, using the first variant as default
        result: dict[str, RouteGroup] = {}
        for group_name, variants in grouped.items():
            first = next(iter(variants))
            result[group_name] = RouteGroup(default=first, routes=variants)

        return result

    def _get_category(self, category: str) -> dict[str, RouteGroup]:
        try:
            return self._categories[category]
        except KeyError:
            raise ValueError(
                f"Unknown category {category!r}. "
                f"Valid categories: {self.list_categories()}."
            ) from None


# Singleton instance
REGISTRY = RouteRegistry()


# ------------------------------------------------------------------
# Backward-compatible API (scoped to natural-gas)
# ------------------------------------------------------------------

# Map old group names to their (category-group, default-variant) in the
# new registry.  The old ROUTE_REGISTRY used friendly names like
# "consumption" -> "natural-gas/cons/sum".  The new registry uses the
# raw API segment names ("cons").
_LEGACY_GROUP_MAP: dict[str, tuple[str, str]] = {
    "consumption": ("cons", "sum"),
    "movements": ("move", "ist"),
    "production": ("prod", "sum"),
    "storage": ("stor", "wkly"),
    "prices": ("pri", "sum"),
    "summary": ("sum", "lsum"),
    "exploration": ("enr", "sum"),
}


def resolve_route(group: str, variant: str | None = None) -> str:
    """Resolve a natural-gas route (backward-compatible).

    Accepts legacy group names (``"consumption"``, ``"prices"``, etc.)
    and maps them to the new registry.
    """
    if group in _LEGACY_GROUP_MAP:
        new_group, default_variant = _LEGACY_GROUP_MAP[group]
        return REGISTRY.resolve(
            "natural-gas", new_group, variant or default_variant
        )
    return REGISTRY.resolve("natural-gas", group, variant)


def list_routes(group: str | None = None) -> dict[str, list[str]]:
    """List natural-gas route variants (backward-compatible)."""
    if group is None:
        return {
            legacy: sorted(
                REGISTRY._categories.get("natural-gas", {})
                .get(new_group, RouteGroup(default="", routes={}))
                .routes
            )
            for legacy, (new_group, _) in _LEGACY_GROUP_MAP.items()
        }
    if group in _LEGACY_GROUP_MAP:
        new_group, _ = _LEGACY_GROUP_MAP[group]
        groups = REGISTRY._categories.get("natural-gas", {})
        rg = groups.get(new_group)
        if rg is None:
            raise ValueError(f"Unknown route group {group!r}.")
        return {group: sorted(rg.routes)}
    raise ValueError(
        f"Unknown route group {group!r}. "
        f"Valid groups: {sorted(_LEGACY_GROUP_MAP)}."
    )
